import { User, OnlineStatus } from '../types/codegen.types';

const users: any[] = [
  {
    id: '1',
    publicAddress: '0x1',
    username: '1',
    nonce: 1,
    firstName: 'test',
    lastName: 'test',
    bio: 'test',
    profilePicture: 'https://www.google.com',
    settings: {
      onlineStatus: OnlineStatus.Away,
      isPrivate: true,
      canReceiveFriendRequests: true,
    },
    friends: [{ id: '2' }, { id: '3' }, { id: '4' }] as User[],
    createdAt: '2021-08-01T00:00:00.000Z',
    updatedAt: '2021-08-01T00:00:00.000Z',
    // friendRequests: [],
    // reviews: [],
    // achievements: [],
    // libraryGames: [],
    // favoriteGames: [],
    // ownedAddons: [],
    // favoriteAddons: [],
    // createdOrgs: [],
    // joinedOrgs: [],
    // totalAchievements: null,
    // totalHoursPlayed: 10,
    // totalFriends: 2,
  },
  {
    id: '2',
    publicAddress: '0x2',
    username: '2',
    nonce: 1,
    firstName: 'test',
    lastName: 'test',
    bio: 'test',
    profilePicture: 'https://www.google.com',
    settings: {
      onlineStatus: OnlineStatus.Online,
      isPrivate: true,
      canReceiveFriendRequests: true,
    },
    friends: [{ id: '1' }, { id: '4' }] as User[],
    createdAt: '2021-08-01T00:00:00.000Z',
    updatedAt: '2021-08-01T00:00:00.000Z',
  },
  {
    id: '3',
    publicAddress: '0x3',
    username: '3',
    nonce: 1,
    firstName: 'test',
    lastName: 'test',
    bio: 'test',
    profilePicture: 'https://www.google.com',
    settings: {
      onlineStatus: OnlineStatus.Away,
      isPrivate: true,
      canReceiveFriendRequests: true,
    },
    friends: [{ id: '1' }, { id: '4' }, { id: '5' }] as User[],
    createdAt: '2021-08-01T00:00:00.000Z',
    updatedAt: '2021-08-01T00:00:00.000Z',
  },
  {
    id: '4',
    publicAddress: '0x4',
    username: '4',
    nonce: 1,
    firstName: 'test',
    lastName: 'test',
    bio: 'test',
    profilePicture: 'https://www.google.com',
    settings: {
      onlineStatus: OnlineStatus.Offline,
      isPrivate: true,
      canReceiveFriendRequests: true,
    },
    friends: [{ id: '1' }, { id: '2' }, { id: '3' }] as User[],
    createdAt: '2021-08-01T00:00:00.000Z',
    updatedAt: '2021-08-01T00:00:00.000Z',
  },
  {
    id: '5',
    publicAddress: '0x5',
    username: '5',
    nonce: 1,
    firstName: 'test',
    lastName: 'test',
    bio: 'test',
    profilePicture: 'https://www.google.com',
    settings: {
      onlineStatus: OnlineStatus.Offline,
      isPrivate: true,
      canReceiveFriendRequests: true,
    },
    friends: [{ id: '3' }] as User[],
    createdAt: '2021-08-01T00:00:00.000Z',
    updatedAt: '2021-08-01T00:00:00.000Z',
  },
];
